#!/usr/bin/env python3
"""
Cleanup Script for SpeedyFibonacci

Removes generated files, caches, and build artifacts.

Usage:
    python scripts/clean.py [--all] [--results] [--build] [--cache]

Options:
    --all       Remove everything (results, build, cache)
    --results   Remove generated results (CSV, PNG files)
    --build     Remove build artifacts (*.so, *.c, build/)
    --cache     Remove Python cache (__pycache__, *.pyc)

Author: SpeedyFibonacci Contributors
License: MIT
"""

import argparse
import shutil
import sys
from pathlib import Path


project_root = Path(__file__).parent.parent


def clean_results():
    """Remove generated result files."""
    results_dir = project_root / "results"

    if results_dir.exists():
        count = 0
        for pattern in ["*.csv", "*.png", "*.jpg"]:
            for f in results_dir.glob(pattern):
                f.unlink()
                count += 1
                print(f"Removed: {f}")

        print(f"Cleaned {count} result file(s)")
    else:
        print("No results directory found")


def clean_build():
    """Remove build artifacts."""
    count = 0

    # Remove .so files (compiled extensions)
    for so_file in project_root.rglob("*.so"):
        so_file.unlink()
        count += 1
        print(f"Removed: {so_file}")

    # Remove .pyd files (Windows)
    for pyd_file in project_root.rglob("*.pyd"):
        pyd_file.unlink()
        count += 1
        print(f"Removed: {pyd_file}")

    # Remove .c files generated by Cython (but not our source files)
    cython_dir = project_root / "techniques" / "09_cython_optimized"
    for c_file in cython_dir.glob("*.c"):
        c_file.unlink()
        count += 1
        print(f"Removed: {c_file}")

    # Remove build directory
    build_dir = project_root / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)
        count += 1
        print(f"Removed: {build_dir}")

    # Remove egg-info
    for egg_dir in project_root.glob("*.egg-info"):
        shutil.rmtree(egg_dir)
        count += 1
        print(f"Removed: {egg_dir}")

    # Remove dist
    dist_dir = project_root / "dist"
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
        count += 1
        print(f"Removed: {dist_dir}")

    print(f"Cleaned {count} build artifact(s)")


def clean_cache():
    """Remove Python cache files."""
    count = 0

    # Remove __pycache__ directories
    for cache_dir in project_root.rglob("__pycache__"):
        shutil.rmtree(cache_dir)
        count += 1
        print(f"Removed: {cache_dir}")

    # Remove .pyc files
    for pyc_file in project_root.rglob("*.pyc"):
        pyc_file.unlink()
        count += 1
        print(f"Removed: {pyc_file}")

    # Remove .pyo files
    for pyo_file in project_root.rglob("*.pyo"):
        pyo_file.unlink()
        count += 1
        print(f"Removed: {pyo_file}")

    # Remove pytest cache
    pytest_cache = project_root / ".pytest_cache"
    if pytest_cache.exists():
        shutil.rmtree(pytest_cache)
        count += 1
        print(f"Removed: {pytest_cache}")

    # Remove mypy cache
    mypy_cache = project_root / ".mypy_cache"
    if mypy_cache.exists():
        shutil.rmtree(mypy_cache)
        count += 1
        print(f"Removed: {mypy_cache}")

    # Remove Numba cache
    for nbc_dir in project_root.rglob("*.nbc"):
        nbc_dir.unlink()
        count += 1
        print(f"Removed: {nbc_dir}")

    for nbi_dir in project_root.rglob("*.nbi"):
        nbi_dir.unlink()
        count += 1
        print(f"Removed: {nbi_dir}")

    print(f"Cleaned {count} cache item(s)")


def main():
    parser = argparse.ArgumentParser(
        description="Clean SpeedyFibonacci generated files"
    )

    parser.add_argument(
        '--all', '-a',
        action='store_true',
        help='Remove all generated files'
    )

    parser.add_argument(
        '--results', '-r',
        action='store_true',
        help='Remove generated results (CSV, PNG)'
    )

    parser.add_argument(
        '--build', '-b',
        action='store_true',
        help='Remove build artifacts'
    )

    parser.add_argument(
        '--cache', '-c',
        action='store_true',
        help='Remove Python cache'
    )

    args = parser.parse_args()

    # Default to --all if no options specified
    if not (args.all or args.results or args.build or args.cache):
        args.all = True

    print("SpeedyFibonacci Cleanup")
    print("=" * 40)

    if args.all or args.cache:
        print("\nCleaning cache...")
        clean_cache()

    if args.all or args.build:
        print("\nCleaning build artifacts...")
        clean_build()

    if args.all or args.results:
        print("\nCleaning results...")
        clean_results()

    print("\nCleanup complete!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
